"""annotation_sets: drop unique book_id

Revision ID: 0ac5706dd1de
Revises: c37fe2bb729b
Create Date: 2025-12-31 12:16:56.386242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac5706dd1de'
down_revision: Union[str, Sequence[str], None] = 'c37fe2bb729b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation_sets', 'book_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_annotation_set_book'), 'annotation_sets', type_='unique')
    op.create_index(op.f('ix_annotation_sets_file_path'), 'annotation_sets', ['file_path'], unique=True)
    op.drop_constraint(op.f('annotation_sets_book_id_fkey'), 'annotation_sets', type_='foreignkey')
    op.create_foreign_key(
        op.f('annotation_sets_book_id_fkey'),
        'annotation_sets', 
        'books', 
        ['book_id'], 
        ['id'], 
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('annotation_sets_book_id_fkey'), 'annotation_sets', type_='foreignkey')
    op.create_foreign_key(
        op.f('annotation_sets_book_id_fkey'), 
        'annotation_sets', 
        'books', 
        ['book_id'], 
        ['id'], 
        ondelete='SET NULL',
    )
    op.drop_index(op.f('ix_annotation_sets_file_path'), table_name='annotation_sets')
    op.create_unique_constraint(op.f('uq_annotation_set_book'), 'annotation_sets', ['book_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('annotation_sets', 'book_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
