"""chapters: parent_id ON DELETE CASCADE

Revision ID: 68a2e4e2bb4c
Revises: 55a253198a99
Create Date: 2025-09-26 12:33:58.792443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a2e4e2bb4c'
down_revision: Union[str, Sequence[str], None] = '55a253198a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_parent_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'chapters', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_parent_id_fkey'), 'chapters', 'chapters', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
