"""chapters parent ondelete set null and unique constraint

Revision ID: 712a71d3547d
Revises: 21768e6a9349
Create Date: 2026-01-09 08:06:03.180487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712a71d3547d'
down_revision: Union[str, Sequence[str], None] = '21768e6a9349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_chapters_book_chapter_number', 
        'chapters', 
        ['book_id', 'chapter_number']
    )
    op.drop_constraint(op.f('chapters_parent_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(
        op.f('chapters_parent_id_fkey'), 
        'chapters', 
        'chapters', 
        ['parent_id'], 
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_parent_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(
        op.f('chapters_parent_id_fkey'), 
        'chapters', 
        'chapters', 
        ['parent_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    op.drop_constraint('uq_chapters_book_chapter_number', 'chapters', type_='unique')
    # ### end Alembic commands ###
