from typing import Protocol, Optional
from app.domain.entities.annotation_set import AnnotationSet

class AnnotationSetRepository(Protocol):
    def add(self, annotation_set: AnnotationSet) -> None: ...
    def get(self, annotation_set_id: str) -> Optional[AnnotationSet]: ...
    def get_by_file_path(self, file_path: str) -> Optional[AnnotationSet]: ...
    def update(self, annotation_set: AnnotationSet) -> bool: ...
    def delete(self, annotation_set: AnnotationSet) -> bool: ...

    def list_for_book(self, book_id: str) -> list[AnnotationSet]: ...