from app.domain.entities.book import Book
from typing import Protocol, Optional, Iterable

class BookRepository(Protocol):
    def add(self, book: Book) -> None: ...
    def get(self, book_id: str) -> Optional[Book]: ...
    def get_by_title(self, title: str) -> Optional[Book]: ...
    def update(self, book: Book) -> bool: ...
    def delete(self, book_id: str) -> bool: ...

    def list_books_for_owner(self, owner_id) -> Iterable[Book]: ...