from typing import Protocol, Iterable, Optional

from app.domain.entities.chapter import Chapter

class ChapterRepository(Protocol):
    def add(self, chapter: Chapter) -> None:...
    def get(self, chapter_id: str) -> Optional[Chapter]: ...

    def delete_for_book(self, book_id: str) -> bool: ...
    def add_many(self, chapters: Iterable[Chapter]) -> int: ...

    def list_for_book(self, book_id: str) -> Iterable[Chapter]: ...