from typing import Protocol, Optional, Tuple, Dict
from app.domain.value_objects.quotation_marks import QuoteType

class ExcelQuotesFootnotesPort(Protocol):
    def export_from_markdown(self, md_path: str, quote_type: QuoteType,  excel_path: Optional[str] = None) -> Tuple[str, Dict]: ...
    def apply_translations_from_excel(self, excel_path: str, md_input_path: str, md_output_path: Optional[str] = None) -> str: ...