from typing import Protocol

class FileStorage(Protocol):
    def save(self, owner_id: str, filename: str, content: bytes, content_type: str | None = None) -> str: ...
    def delete(self, storage_path: str) -> None: ...

    def read_bytes(self, storage_path: str) -> bytes: ...
    def read_text(self, storage_path: str, encoding: str = "utf-8") -> str: ...