from typing import Protocol

class FileStorage(Protocol):
    def save(self, owner_id: str, filename: str, content: bytes, content_type: str | None = None) -> str: ...
    def delete(self, storage_path: str) -> None: ...