from app.domain.entities.file import File
from app.domain.value_objects.file_kind import FileKind
from typing import Optional, Iterable, Protocol

class FileRepository(Protocol):
    def add(self, file: File) -> None: ...
    def get(self, file_id: str) -> Optional[File]: ...
    def update(self, file: File) -> None: ...
    def delete(self, file_id: str) -> None: ...

    def save(self, destination_name: str) -> str: ...
    def open(self, path: str) -> str: ...

    def list_files_for_owner(self, owner_id: str, kind: Optional[FileKind], limit: Optional[int]) -> Iterable[File]: ...
    def list_files_for_book(self, book_id: str, kind: Optional[FileKind], limit: Optional[int]) -> Iterable[File]: ...