from typing import Protocol

class MarkdownAnalyzerPort(Protocol):
    def load_text(self) -> str: ...
    def identify_headers(self) -> list[dict[str, any]]: ...
    def identify_footnotes(self) -> list[dict[str, any]]: ...