from typing import Protocol

class MarkdownAnalyzerPort(Protocol):
    def load_text(self, file_path: str) -> str: ...
    def identify_headers(self, markdown_text: str) -> list[dict[str, any]]: ...
    def identify_footnotes(self, markdown_text: str) -> list[dict[str, any]]: ...