from typing import Protocol
import asyncio

class ProgressTrackerPort(Protocol):
    async def start(self, task_id: str, initial_message: str = "Started") -> None: ...
    async def update(self, task_id: str, progress: int, message: str) -> None: ...
    async def complete(self, task_id: str, message: str = "Complete") -> None: ...
    async def fail(self, task_id: str, message: str = "Failed") -> None: ...
    async def subscribe(self, task_id: str) -> asyncio.Queue: ...
    async def unsubscribe(self, task_id: str, queue: asyncio.Queue) -> None: ...
    
    def has_task(self, task_id: str) -> bool: ...