from app.domain.entities.user import User
from typing import Protocol, Optional, Iterable

class UserRepository(Protocol):
    def add(self, user: User) -> None: ...
    def get(self, user_id: str) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def update(self, user: User) -> bool: ...
    def delete(self, user_id: str) -> bool: ...

    def list_paginated_filtered(self, limit: int, offset: int, email_like: Optional[str]) -> Iterable[User]: ...